# Ephemeral DB primarily for local testing and development deployments.

apiVersion: skaffold/v2beta29 
kind: Config

deploy:
  helm:
    releases:
      - name: skaffold-init-db
        namespace: skaffold-init-namespace
        remoteChart: bitnami/postgresql
        createNamespace: true
        version: 11.6.10
        setValues:
          postgresqlUsername: admin
          postgresqlPassword: admin
          postgresqlDatabase: polardb_catalog
          image.tag: 12
      
